### ISSUE TITLE
Unable to set up

### ISSUE THREAD

**Issue by nolyn** [mbourqui/django-publications-bootstrap#50]
Hi, I'd love to try this out. What I did:
```
mkvirtualenv djangoTestPublicationsBootstrap
pip install django-publications-bootstrap
mkdir publicationsBootstrap
cd publicationsBootstrap
django-admin startproject test
django-admin startproject testPublications
cd testPublications
# did the changes to settings.py and url.py
./manage.py migrate publications_bootstrap

Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/myuser/Envs/djangoTestPublicationsBootstrap/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/myuser/Envs/djangoTestPublicationsBootstrap/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/myuser/Envs/djangoTestPublicationsBootstrap/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/myuser/Envs/djangoTestPublicationsBootstrap/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/myuser/Envs/djangoTestPublicationsBootstrap/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/myuser/Envs/djangoTestPublicationsBootstrap/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/myuser/Envs/djangoTestPublicationsBootstrap/lib/python3.6/site-packages/publications_bootstrap/models/__init__.py", line 4, in <module>
    from .catalog import Catalog
  File "/home/myuser/Envs/djangoTestPublicationsBootstrap/lib/python3.6/site-packages/publications_bootstrap/models/catalog.py", line 4, in <module>
    from .publication import Publication
  File "/home/myuser/Envs/djangoTestPublicationsBootstrap/lib/python3.6/site-packages/publications_bootstrap/models/publication.py", line 20, in <module>
    class Publication(models.Model):
  File "/home/myuser/Envs/djangoTestPublicationsBootstrap/lib/python3.6/site-packages/publications_bootstrap/models/publication.py", line 55, in Publication
    type = models.ForeignKey(Type, db_index=True)
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

No idea what the problem is. And by the way, I think it should be "Add publications_bootstrap", not "Add publications-bootstrap"

My packages:
```
pip freeze
Django==2.0.4
django-countries==5.3
django-echoices==2.2.5
django-ordered-model==1.4.3
django-publications-bootstrap==2.2.2
Pillow==5.1.0
pytz==2018.4
six==1.11.0

```

**Comment by mbourqui** [comment]
Hi,
Thank you for your interest in my fork, and sorry for the late reply.
The issue you have is with Django 2.0. The fix is actually already on master, but not yet packaged and released on PyPI. So far, you have two alternatives to solve your Django 2 issue:
* install directly from the repository
* give me 2 more days, and I will publish a new release

**Comment by mbourqui** [comment]
I just released a new version, please check it out and let me know if have any difficulties.

**Comment by nolyn** [comment]
that works! thx. i'll want to integrate it into our website :smiley:. We are using django-cms and i'm still learning about that though I've used django before. And I have to learn a bit about bootstrap I guess. 
Thanks again!
